### ISSUE TITLE
KFoldBySortedValue issue

### ISSUE THREAD

**Issue by thundo** [neptune-ml/open-solution-salt-detection#22]
Hello neptune-team, I'm a fellow Kaggler. I find your contribution very valuable and I'm exploring your code. 

I stumbled on `KFoldBySortedValue` while doing static analysis.

Shouldn't

https://github.com/neptune-ml/open-solution-salt-detection/blob/239016c742d913a6822d33edb6f3beaac959cc9b/src/utils.py#L416

be

```python
def get_n_splits(self, X=None, y=None, groups=None):
        return self.n_splits
 ```

Btw... did you get any improvement in sorting by depth the dataset?

Thank you

**Comment by jakubczakon** [comment]
Hi you are right I'll fix that. I didn't find this bug because get_n_splits() is never actually called.

Depth-wise I will finally get back to this competition this week so I may get some improvements (hopefully). I will write about it on the forums either way.
