### ISSUE TITLE
Can not find the 'metadata.csv'

### ISSUE THREAD

**Issue by qinhui99** [neptune-ml/open-solution-salt-detection#23]
When I run the command 'python main.py -- train--pipeline_name unet', I got the error "Can not find the 'metadata.csv'" .   I checked  all the files of salt-detection and still can not find it.  Did I miss something important?

**Comment by areveillon** [comment]
in main.py line 20 you can add : 

def train(pipeline_name, dev_mode):
    pipeline_manager.prepare_metadata()
    pipeline_manager.train(pipeline_name, dev_mode)

Prepare_metadata() was never called

**Comment by qinhui99** [comment]
It works. Thanks.
